version: "3.5"
services:
  placeholderapi:
    build: ./placeholderapi
    ports:
      - "8080:8080"
    networks:
      - nats
  nats:
    image: nats:2.9.20
    ports:
      - "8222:8222"
      - "4222:4222"
    expose:
      - "8222"
      - "4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks:
      - nats
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - nats
    restart: unless-stopped

networks:
  nats:
    name: nats

volumes:
  postgres: